name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm nx affected --target=lint
      - run: pnpm nx affected --target=test
      - run: pnpm nx affected --target=build
      - run: docker build -t acadura-erp apps/acadura-erp
